# Generated by Django 3.1.4 on 2021-01-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
