# Generated by Django 3.1.4 on 2021-01-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankApp', '0002_transfer_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
